// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: contracts/protos/presence_service.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Dial          string                 `protobuf:"bytes,2,opt,name=dial,proto3" json:"dial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectUserRequest) Reset() {
	*x = ConnectUserRequest{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserRequest) ProtoMessage() {}

func (x *ConnectUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserRequest.ProtoReflect.Descriptor instead.
func (*ConnectUserRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectUserRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectUserRequest) GetDial() string {
	if x != nil {
		return x.Dial
	}
	return ""
}

type UserConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnectionResponse) Reset() {
	*x = UserConnectionResponse{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnectionResponse) ProtoMessage() {}

func (x *UserConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnectionResponse.ProtoReflect.Descriptor instead.
func (*UserConnectionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_contracts_protos_presence_service_proto protoreflect.FileDescriptor

const file_contracts_protos_presence_service_proto_rawDesc = "" +
	"\n" +
	"'contracts/protos/presence_service.proto\x12\fcotnracts.v1\"E\n" +
	"\x12ConnectUserRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04dial\x18\x02 \x01(\tR\x04dial\"2\n" +
	"\x16UserConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2`\n" +
	"\vUserService\x12Q\n" +
	"\aConnect\x12 .cotnracts.v1.ConnectUserRequest\x1a$.cotnracts.v1.UserConnectionResponseB1Z/github.com/AGranosik/chat/contracts;contractsv1b\x06proto3"

var (
	file_contracts_protos_presence_service_proto_rawDescOnce sync.Once
	file_contracts_protos_presence_service_proto_rawDescData []byte
)

func file_contracts_protos_presence_service_proto_rawDescGZIP() []byte {
	file_contracts_protos_presence_service_proto_rawDescOnce.Do(func() {
		file_contracts_protos_presence_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protos_presence_service_proto_rawDesc), len(file_contracts_protos_presence_service_proto_rawDesc)))
	})
	return file_contracts_protos_presence_service_proto_rawDescData
}

var file_contracts_protos_presence_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_protos_presence_service_proto_goTypes = []any{
	(*ConnectUserRequest)(nil),     // 0: cotnracts.v1.ConnectUserRequest
	(*UserConnectionResponse)(nil), // 1: cotnracts.v1.UserConnectionResponse
}
var file_contracts_protos_presence_service_proto_depIdxs = []int32{
	0, // 0: cotnracts.v1.UserService.Connect:input_type -> cotnracts.v1.ConnectUserRequest
	1, // 1: cotnracts.v1.UserService.Connect:output_type -> cotnracts.v1.UserConnectionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_protos_presence_service_proto_init() }
func file_contracts_protos_presence_service_proto_init() {
	if File_contracts_protos_presence_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protos_presence_service_proto_rawDesc), len(file_contracts_protos_presence_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protos_presence_service_proto_goTypes,
		DependencyIndexes: file_contracts_protos_presence_service_proto_depIdxs,
		MessageInfos:      file_contracts_protos_presence_service_proto_msgTypes,
	}.Build()
	File_contracts_protos_presence_service_proto = out.File
	file_contracts_protos_presence_service_proto_goTypes = nil
	file_contracts_protos_presence_service_proto_depIdxs = nil
}
