// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: contracts/protos/presence_service.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomsId       []string               `protobuf:"bytes,1,rep,name=rooms_id,json=roomsId,proto3" json:"rooms_id,omitempty"`
	InstanceName  string                 `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectUserRequest) Reset() {
	*x = ConnectUserRequest{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserRequest) ProtoMessage() {}

func (x *ConnectUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserRequest.ProtoReflect.Descriptor instead.
func (*ConnectUserRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectUserRequest) GetRoomsId() []string {
	if x != nil {
		return x.RoomsId
	}
	return nil
}

func (x *ConnectUserRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ConnectUserRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DisconnectUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectUserRequest) Reset() {
	*x = DisconnectUserRequest{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectUserRequest) ProtoMessage() {}

func (x *DisconnectUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectUserRequest.ProtoReflect.Descriptor instead.
func (*DisconnectUserRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{1}
}

func (x *DisconnectUserRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClientsConnectionDestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientsConnectionDestRequest) Reset() {
	*x = ClientsConnectionDestRequest{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsConnectionDestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsConnectionDestRequest) ProtoMessage() {}

func (x *ClientsConnectionDestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsConnectionDestRequest.ProtoReflect.Descriptor instead.
func (*ClientsConnectionDestRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{3}
}

func (x *ClientsConnectionDestRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type UserConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceNames []string               `protobuf:"bytes,1,rep,name=instance_names,json=instanceNames,proto3" json:"instance_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnectionResponse) Reset() {
	*x = UserConnectionResponse{}
	mi := &file_contracts_protos_presence_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnectionResponse) ProtoMessage() {}

func (x *UserConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protos_presence_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnectionResponse.ProtoReflect.Descriptor instead.
func (*UserConnectionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protos_presence_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserConnectionResponse) GetInstanceNames() []string {
	if x != nil {
		return x.InstanceNames
	}
	return nil
}

var File_contracts_protos_presence_service_proto protoreflect.FileDescriptor

const file_contracts_protos_presence_service_proto_rawDesc = "" +
	"\n" +
	"'contracts/protos/presence_service.proto\x12\fcotnracts.v1\"q\n" +
	"\x12ConnectUserRequest\x12\x19\n" +
	"\brooms_id\x18\x01 \x03(\tR\aroomsId\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"4\n" +
	"\x15DisconnectUserRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\".\n" +
	"\x12ConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x1cClientsConnectionDestRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"?\n" +
	"\x16UserConnectionResponse\x12%\n" +
	"\x0einstance_names\x18\x01 \x03(\tR\rinstanceNames2\x92\x02\n" +
	"\vUserService\x12M\n" +
	"\aConnect\x12 .cotnracts.v1.ConnectUserRequest\x1a .cotnracts.v1.ConnectionResponse\x12S\n" +
	"\n" +
	"Disconnect\x12#.cotnracts.v1.DisconnectUserRequest\x1a .cotnracts.v1.ConnectionResponse\x12_\n" +
	"\vIsConnected\x12*.cotnracts.v1.ClientsConnectionDestRequest\x1a$.cotnracts.v1.UserConnectionResponseB1Z/github.com/AGranosik/chat/contracts;contractsv1b\x06proto3"

var (
	file_contracts_protos_presence_service_proto_rawDescOnce sync.Once
	file_contracts_protos_presence_service_proto_rawDescData []byte
)

func file_contracts_protos_presence_service_proto_rawDescGZIP() []byte {
	file_contracts_protos_presence_service_proto_rawDescOnce.Do(func() {
		file_contracts_protos_presence_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protos_presence_service_proto_rawDesc), len(file_contracts_protos_presence_service_proto_rawDesc)))
	})
	return file_contracts_protos_presence_service_proto_rawDescData
}

var file_contracts_protos_presence_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_contracts_protos_presence_service_proto_goTypes = []any{
	(*ConnectUserRequest)(nil),           // 0: cotnracts.v1.ConnectUserRequest
	(*DisconnectUserRequest)(nil),        // 1: cotnracts.v1.DisconnectUserRequest
	(*ConnectionResponse)(nil),           // 2: cotnracts.v1.ConnectionResponse
	(*ClientsConnectionDestRequest)(nil), // 3: cotnracts.v1.ClientsConnectionDestRequest
	(*UserConnectionResponse)(nil),       // 4: cotnracts.v1.UserConnectionResponse
}
var file_contracts_protos_presence_service_proto_depIdxs = []int32{
	0, // 0: cotnracts.v1.UserService.Connect:input_type -> cotnracts.v1.ConnectUserRequest
	1, // 1: cotnracts.v1.UserService.Disconnect:input_type -> cotnracts.v1.DisconnectUserRequest
	3, // 2: cotnracts.v1.UserService.IsConnected:input_type -> cotnracts.v1.ClientsConnectionDestRequest
	2, // 3: cotnracts.v1.UserService.Connect:output_type -> cotnracts.v1.ConnectionResponse
	2, // 4: cotnracts.v1.UserService.Disconnect:output_type -> cotnracts.v1.ConnectionResponse
	4, // 5: cotnracts.v1.UserService.IsConnected:output_type -> cotnracts.v1.UserConnectionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_protos_presence_service_proto_init() }
func file_contracts_protos_presence_service_proto_init() {
	if File_contracts_protos_presence_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protos_presence_service_proto_rawDesc), len(file_contracts_protos_presence_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protos_presence_service_proto_goTypes,
		DependencyIndexes: file_contracts_protos_presence_service_proto_depIdxs,
		MessageInfos:      file_contracts_protos_presence_service_proto_msgTypes,
	}.Build()
	File_contracts_protos_presence_service_proto = out.File
	file_contracts_protos_presence_service_proto_goTypes = nil
	file_contracts_protos_presence_service_proto_depIdxs = nil
}
