syntax = "proto3";

package cotnracts.v1;

option go_package = "github.com/AGranosik/chat/contracts;contractsv1";

service UserService {
  rpc Connect(ConnectUserRequest) returns (ConnectionResponse);
  rpc Disconnect(DisconnectUserRequest) returns (ConnectionResponse);
}


message ConnectUserRequest {
  string room_id = 1;
  string dial = 2;
  string client_id =3;
}

message DisconnectUserRequest {
  string room_id = 1;
  string client_id =2;
}

message ConnectionResponse {
  bool success = 1;
}