syntax = "proto3";

package cotnracts.v1;

option go_package = "github.com/AGranosik/chat/contracts;contractsv1";

service UserService {
  rpc Connect(ConnectUserRequest) returns (ConnectionResponse);
  rpc Disconnect(DisconnectUserRequest) returns (ConnectionResponse);
  rpc IsConnected(ClientsConnectionDestRequest) returns (UserConnectionResponse);
}


message ConnectUserRequest {
  repeated string rooms_id = 1;
  string instance_name = 2;
  string client_id =3;
}

message DisconnectUserRequest {
  string client_id = 1;
}

message ConnectionResponse {
  bool success = 1;
}

message ClientsConnectionDestRequest {
  string room_id = 1;
}

message UserConnectionResponse {
  repeated string instance_names = 1;
}